[general]
live_config_reload = true

[cursor]
style = { shape = "Beam", blinking = "Always" }

[scrolling]
history = 100000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 11.0

[terminal]
# shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux attach || tmux new"] }

[selection]
save_to_clipboard = true
