theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
true-color = true
end-of-line-diagnostics = "hint"
bufferline = "always"
popup-border = "all"
color-modes = true
# rainbow-brackets = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "separator", "spacer", "version-control"]
right = [
    "diagnostics",
    "selections",
    "register",
    "position",
    "total-line-numbers",
    "file-encoding",
]
separator = "-"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
# show hidden files
hidden = false

# [editor.auto-save]
# focus-lost = true
# after-delay.enable = true
# after-delay.timeout = 1000

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "â•Ž"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.lsp]
# display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

# ---
[keys.normal]

# Yazi integration
# Thanks: https://github.com/sxyazi/yazi/pull/2461
"C-y" = [
    ":sh rm -f /tmp/helix-yazi-file",
    ":insert-output %sh{ tmux popup -w 90%% -h 80%% -d \"$PWD\" -E \"tmux new-session yazi --chooser-file=/tmp/helix-yazi-file \\; set status off \\; set pane-border-status off\" }",
    ":sh printf \"\\x1b[?1049h\\x1b[?2004h\" > /dev/tty",
    ":open %sh{ cat /tmp/helix-yazi-file }",
    ":redraw"
]

"C-right" = ["move_next_word_start", "collapse_selection"]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-up" = ["goto_prev_paragraph", "collapse_selection"]
"C-down" = ["goto_next_paragraph", "collapse_selection"]

# lazygit integration (for Tmux)
"C-g" = [":sh tmux popup -w 90%% -h 80%% -d \"$(pwd)\" -E lazygit", ":redraw"]

[keys.normal.space]
q = ":buffer-close"
"\\" = ["select_all", "select_regex"]

[keys.insert]
j = { j = "normal_mode" }
"C-right" = ["move_next_word_start", "collapse_selection"]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-up" = ["goto_prev_paragraph", "collapse_selection"]
"C-down" = ["goto_next_paragraph", "collapse_selection"]
