theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
true-color = true
end-of-line-diagnostics = "hint"
bufferline = "always"
popup-border = "all"
color-modes = true
# rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

# [editor.auto-save]
# focus-lost = true
# after-delay.enable = true
# after-delay.timeout = 1000

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "â•Ž"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

# ---
[keys.normal]

# Yazi integration
# Thanks: https://github.com/sxyazi/yazi/pull/2461
"C-y" = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]

# lazygit integration (for Tmux)
"C-g" = [":sh tmux popup -w 90%% -h 80%% -d \"$(pwd)\" -E lazygit", ":redraw"]

[keys.normal.space]
q = ":buffer-close"

[keys.insert]
j = { j = "normal_mode" }
